#include <unistd.h>
#include <stdio.h>
#include <initGPIO.h>
#include <snes.h>
#include <screen.h>
#include <stdlib.h>
#include <sys/mman.h>
#include "framebuffer.h"
#include <pthread.h>
#include <time.h>
#include "framebuffer.h"
#include <stdlib.h>
#include <sys/mman.h>
#include <gameObject.h>